# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_box.ui'
#
# Created: Mon Jun  9 00:14:20 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(706, 567)
        Dialog.setMinimumSize(QtCore.QSize(706, 560))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabAvailableFunctionalities = QtGui.QWidget()
        self.tabAvailableFunctionalities.setObjectName("tabAvailableFunctionalities")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabAvailableFunctionalities)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeViewAvailableComponents = QtGui.QTreeView(self.tabAvailableFunctionalities)
        self.treeViewAvailableComponents.setMinimumSize(QtCore.QSize(191, 506))
        self.treeViewAvailableComponents.setMaximumSize(QtCore.QSize(235, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.treeViewAvailableComponents.setFont(font)
        self.treeViewAvailableComponents.setObjectName("treeViewAvailableComponents")
        self.horizontalLayout.addWidget(self.treeViewAvailableComponents)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtGui.QLabel(self.tabAvailableFunctionalities)
        self.labelTitle.setMinimumSize(QtCore.QSize(411, 41))
        self.labelTitle.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setText("")
        self.labelTitle.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.plainTextDescription = QtGui.QPlainTextEdit(self.tabAvailableFunctionalities)
        self.plainTextDescription.setEnabled(True)
        self.plainTextDescription.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monotype Koufi")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.plainTextDescription.setFont(font)
        self.plainTextDescription.setAutoFillBackground(False)
        self.plainTextDescription.setFrameShape(QtGui.QFrame.NoFrame)
        self.plainTextDescription.setFrameShadow(QtGui.QFrame.Sunken)
        self.plainTextDescription.setLineWidth(1)
        self.plainTextDescription.setUndoRedoEnabled(False)
        self.plainTextDescription.setReadOnly(True)
        self.plainTextDescription.setPlainText("")
        self.plainTextDescription.setBackgroundVisible(False)
        self.plainTextDescription.setObjectName("plainTextDescription")
        self.verticalLayout.addWidget(self.plainTextDescription)
        self.buttonActivation = QtGui.QPushButton(self.tabAvailableFunctionalities)
        self.buttonActivation.setEnabled(False)
        self.buttonActivation.setMinimumSize(QtCore.QSize(421, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.buttonActivation.setFont(font)
        self.buttonActivation.setCheckable(True)
        self.buttonActivation.setDefault(False)
        self.buttonActivation.setFlat(False)
        self.buttonActivation.setObjectName("buttonActivation")
        self.verticalLayout.addWidget(self.buttonActivation)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabAvailableFunctionalities, "")
        self.tabDebugInfo = QtGui.QWidget()
        self.tabDebugInfo.setObjectName("tabDebugInfo")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabDebugInfo)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textDebugInfo = QtGui.QTextEdit(self.tabDebugInfo)
        self.textDebugInfo.setUndoRedoEnabled(False)
        self.textDebugInfo.setReadOnly(True)
        self.textDebugInfo.setAcceptRichText(False)
        self.textDebugInfo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textDebugInfo.setObjectName("textDebugInfo")
        self.horizontalLayout_4.addWidget(self.textDebugInfo)
        self.tabWidget.addTab(self.tabDebugInfo, "")
        self.tabInfos = QtGui.QWidget()
        self.tabInfos.setObjectName("tabInfos")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabInfos)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tabInfos)
        self.plainTextEdit.setBackgroundVisible(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_5.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tabInfos, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonActivation.setText(QtGui.QApplication.translate("Dialog", "Statut", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAvailableFunctionalities), QtGui.QApplication.translate("Dialog", "Fonctionnalités", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDebugInfo), QtGui.QApplication.translate("Dialog", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfos), QtGui.QApplication.translate("Dialog", "A propos", None, QtGui.QApplication.UnicodeUTF8))

